### ISSUE TITLE
Ampersand in title causing handle issue

### ISSUE THREAD

**Issue by jude86-7** [symphonycms/selectbox_link_field#82]
I have two sections:

section 1 - text input (SBL for section 2)
section 2 - SBL, text area

Text input on section 1 is;
value = title &amp; text
handle = title-and-text

This is correct. However if I select this value for the SBL in section 2 I get the following output;
value = title &amp; text
handle = title-and-amp-text

Note the extra 'amp' in the handle when using SBL. I think it has to do with the following line in the code (selectbox_link_field\fields\field.selectbox_link.php);

line 341: $value2 = General::sanitize(General::reverse_sanitize($value));

If I uncomment this line the handle is fixed, however it looks like this line was put in to fix a major security issue. So I really need to keep the line in, has anyone come across this before or know how I could fix this without causing any security problems?

Many thanks

**Comment by nitriques** [comment]
This is pretty weird.

Looking at the related issue I was proposing:

> Why not try prepareTextValue before ? it should already be "clean"

I think this would be the safest route.. Or we could fix the bug in reverse_sanitize...

**Comment by jude86-7** [comment]
Thanks for coming back to me on this. sorry to be a pain when you say;

> Why not try prepareTextValue before ? it should already be "clean"

What do you mean? I'm very new to the extension side of symphony I'm afraid but willing to learn more. Do I need to call the prepareTextValue function earlier or something?

**Comment by nitriques** [comment]
> Do I need to call the prepareTextValue function earlier or something?

Yes, I think that's what we need. `prepareTextValue` was added after this extension was coded, hence, it did not exist at the time. Line 324 really should call `prepareTextValue`...

But that won't fix our problem... I've setup this test

```php
<?php

    // Find out where we are:
    define('DOCROOT', __DIR__);

    // Include autoloader:
    require_once DOCROOT . '/vendor/autoload.php';


    echo General::reverse_sanitize('test & value') . PHP_EOL;
    echo General::sanitize(General::reverse_sanitize('test & value')) . PHP_EOL;
```

and it yeilds what you'd except

```
test & value
test &amp; value
```

>  I get the following output;

You are talking about data source output right ? Thanks.

**Comment by nitriques** [comment]
>  I'm afraid but willing to learn more. 

We all started there at some point. We are here to help as much as we can!

**Comment by nitriques** [comment]
Also it's safe to call sanitize multiple times. I've added

```php
    echo General::sanitize(General::sanitize('test & value')) . PHP_EOL;
    echo General::sanitize(General::sanitize(General::sanitize('test & value'))) . PHP_EOL;
```

outputs

```
test &amp; value
test &amp; value
```

**Comment by nitriques** [comment]
Boy do we need unit tests...

**Comment by jude86-7** [comment]
thank you for your help, it's much appreciated, I understand a little more. However I still can't seem to get the problem fixed, I changed line 324 to the following

`$value = $field->prepareTextValue(`

and used this below;

`$value = General::reverse_sanitize($value);
$value = General::sanitize(General::reverse_sanitize($value));`

However I'm still getting an incorrect data source output. The main value is correct showing;

test &amp; value

But the handle is incorrect showing 

test-and-amp-value

**Comment by nitriques** [comment]
> But the handle is incorrect showing

Where ? In the datasource ?

**Comment by jude86-7** [comment]
Sorry I've been away for a few days, please find ?debug xml below;

`<featured-members-list>
        <pagination total-entries="2" total-pages="1" entries-per-page="6" current-page="1" />
        <section id="27" handle="featured-members">Featured Members</section>
        <entry id="2198">
            <featured-member-select-member>
                <item id="2068" handle="dodd-and-amp-co" section-handle="members" section-name="Members">Dodd &amp; Co</item>
            </featured-member-select-member>
            <featured-member-start-date iso="2016-04-19T16:30:52+01:00" timestamp="1461079852" time="16:30" weekday="2" offset="+0100">2016-04-19</featured-member-start-date>
            <featured-member-end-date iso="2016-05-19T16:30:52+01:00" timestamp="1463671852" time="16:30" weekday="4" offset="+0100">2016-05-19</featured-member-end-date>
        </entry>
        <entry id="2199">
            <featured-member-select-member>
                <item id="2145" handle="j-and-amp-j-graham-ltd" section-handle="members" section-name="Members">J &amp; J Graham Ltd</item>
            </featured-member-select-member>
            <featured-member-start-date iso="2016-04-19T14:09:28+01:00" timestamp="1461071368" time="14:09" weekday="2" offset="+0100">2016-04-19</featured-member-start-date>
            <featured-member-end-date iso="2016-05-19T14:09:28+01:00" timestamp="1463663368" time="14:09" weekday="4" offset="+0100">2016-05-19</featured-member-end-date>
        </entry>
    </featured-members-list>`

Thanks

**Comment by nitriques** [comment]
Thanks this helps a lot! I'll try to reproduce it

**Comment by nitriques** [comment]
I confirm I was able to reproduce.

```xml
        <entry id="391">
            <relation>
                <item id="390" handle="lorem-and-amp-hipster" section-handle="test" section-name="test">Lorem &amp; Hipster</item>
            </relation>
        </entry>
```

**Comment by nitriques** [comment]
I think I've figured it out. We need to reverse_sanitize before creating the handle. Creating a handle on a sanitize value does not produce the right output.

Can you test the latest `integration` branch and confirm it fixes the issue on your end too ? Thanks!

**Comment by jude86-7** [comment]
That's great, I can confirm that the integration branch is working correctly and fixes the issue at my end.

Thank you so much for your help!

**Comment by nitriques** [comment]
Awesome! I'll release ASAP. Thanks.

**Comment by nitriques** [comment]
It's release under `2.0.0`

**Comment by jude86-7** [comment]
Excellent, thank you for all your help :+1:

**Comment by nitriques** [comment]
Thanks for reporting the issue!
